### ISSUE TITLE
Android: Compatibility with PhoneGap Push Plugin

### ISSUE THREAD

**Issue by jefflinwood** [jefflinwood/twilio-voice-phonegap-plugin#21]
Both plugins have the GcmReceiver

**Comment by jefflinwood** [comment]
Similar issue from Intercom's Cordova Plugin

https://github.com/phonegap/phonegap-plugin-push/issues/1640

**Comment by kshaaban-** [comment]
I copied over the solution from the referenced issue.

The problem now is when building the cordova app there's a conflict in the manifest

[phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push/blob/master/plugin.xml#L43-L48) has the following configuration:
```xml
<receiver android:name="com.google.android.gms.gcm.GcmReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
    <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
        <category android:name="${applicationId}"/>
    </intent-filter>
</receiver>
```

While this plugin has
```xml
<receiver
        android:name="com.google.android.gms.gcm.GcmReceiver"
        android:exported="true"
        android:permission="com.google.android.c2dm.permission.SEND">
        <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

        <category android:name="$PACKAGE_NAME" />
    </intent-filter>
</receiver>
```

I ended up commenting out the one in `phonegap-plugin-push` for now and the build finished successfully & upon testing I received notfications successfully from both plugins.

Unsure how to fix the manifest configuration stuff.

**Comment by jefflinwood** [comment]
Hi @kshaaban - did you see that Intercom just addressed their issue a different way:

https://github.com/intercom/intercom-cordova/pull/166/files
