### ISSUE TITLE
Syntax error in SoundPoolManager.java

### ISSUE THREAD

**Issue by ansongoldade** [jefflinwood/twilio-voice-phonegap-plugin#46]
https://github.com/jefflinwood/twilio-voice-phonegap-plugin/blob/e815924c99ef5e3b32ba6320c3d6b7c928b3faa0/src/android/com/phonegap/plugins/twiliovoice/SoundPoolManager.java#L81

Should be `public boolean isRinging() {` instead of `public booleanisRinging() {`

Found this when trying to build a project that depends on this package.

**Comment by jefflinwood** [comment]
Yep! Fixed in 1c48a94

Thanks!
